In [ ]:
# Kishan Chand                          Assignment                        Feb26-23

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [37]:
n=len(list_)
for i in range(n):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [38]:
n=len(array_list)
for i in range(n):
    print(type(array_list[i]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Q3. Considering the following changes in the variable, array_list:

   ## array_list = np.array(object = list_, dtype = int)
    
## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [41]:
array_list1 = np.array(object = list_, dtype = int)
x =len(array_list1)
x

5

In [42]:
for i in range(x):
    print(type(array_list1[i]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [40]:
type(list_)

list

In [44]:
for i in range(len(list_)):
    print(type(list_[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


## Q 4. Write a code to find the following characteristics of variable, num_array:
## (i) shape    
## (ii) size

In [46]:
array_list1.shape

(5,)

In [48]:
array_list1.size

5

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
 ## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [50]:
import numpy as np
z_array =np.zeros((3,3))
z_array


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
import numpy as np
r_array =np.random.randint(3,10,(3,3))
r_array


array([[9, 8, 3],
       [4, 7, 7],
       [4, 4, 3]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [64]:
identity_matrix =np.eye(5,5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])